// API
export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

// CARRITO
export const AGREGAR_PRODUCTO_CARRITO = 'AGREGAR_PRODUCTO_CARRITO';
export const AUMENTAR_CANTIDAD_CARRITO = 'AUMENTAR_CANTIDAD_CARRITO';
export const DISMINUIR_CANTIDAD_CARRITO = 'DISMINUIR_CANTIDAD_CARRITO';
